from abc import ABC, abstractmethod


class AbstractExecutor(ABC):
    @abstractmethod
    async def place_order(self, side: str, qty: float): ...
    @abstractmethod
    async def close_position(self): ...
    @abstractmethod
    def update_mark_price(self, mark_price: float): ...
    @abstractmethod
    def get_position(self) -> dict: ...
    @abstractmethod
    def get_balance(self) -> float: ...
